server:
  port: 9000

spring:
  application:
    name: demo

  sql:
    init:
      platform: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/springboot?autoReconnect=true&setTimezone=Asia/Seoul # 변경해주세요
    username: test # Database ID
    password: test1234^^ # Database Password
    driver-class-name: com.mysql.cj.jdbc.Driver